# Generated by Django 3.1.3 on 2020-12-02 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='day',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='post',
            name='month',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('world', 'WORLD'), ('environment', 'ENVIRONMENT'), ('technology', 'TECHNOLOGY'), ('design', 'DESIGN'), ('culture', 'CULTURE'), ('business', 'BUSINESS'), ('politics', 'POLITICS'), ('opinion', 'OPINION'), ('science', 'SCIENCE'), ('health', 'HEALTH'), ('style', 'STYLE'), ('travel', 'TRAVEL')], default='WORLD', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique_for_date='published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
