# Generated by Django 3.1.3 on 2020-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201202_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('world', 'WORLD'), ('environment', 'ENVIRONMENT'), ('technology', 'TECHNOLOGY'), ('design', 'DESIGN'), ('culture', 'CULTURE'), ('business', 'BUSINESS'), ('politics', 'POLITICS'), ('opinion', 'OPINION'), ('science', 'SCIENCE'), ('health', 'HEALTH'), ('style', 'STYLE'), ('travel', 'TRAVEL')], default='World', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
