# Generated by Django 3.1.3 on 2020-12-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201204_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreportrecord',
            name='published',
        ),
    ]
