# Generated by Django 3.1.3 on 2021-01-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='st_name',
        ),
    ]
