# Generated by Django 3.1.3 on 2021-01-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210129_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='st_name',
            new_name='name',
        ),
    ]
